openapi: 3.0.3
info:
  title: CV API
  version: 1.0.0
  description: >
    Public CV API + CV-scoped chat. This API is designed for a CV website (Next.js) with a backend in .NET.
    OpenAI keys must exist only in the backend service.

servers:
  - url: http://localhost:5080
    description: Local development (adjust port if needed)

tags:
  - name: Health
  - name: CV
  - name: Chat

paths:
  /health:
    get:
      tags: [Health]
      summary: Health check
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /api/v1/cv:
    get:
      tags: [CV]
      summary: Get full CV document (bilingual)
      parameters:
        - in: query
          name: lang
          required: false
          schema:
            type: string
            enum: [es, en]
          description: Language (default: es)
      responses:
        "200":
          description: CV document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CvDocument"
        "400":
          description: Invalid language
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/cv/sections:
    get:
      tags: [CV]
      summary: Get CV sections (useful for incremental loading)
      parameters:
        - in: query
          name: lang
          required: false
          schema:
            type: string
            enum: [es, en]
          description: Language (default: es)
      responses:
        "200":
          description: CV sections
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CvSectionsResponse"

  /api/v1/chat/completions:
    post:
      tags: [Chat]
      summary: CV-scoped chat completion (public)
      description: >
        Returns an assistant message constrained to the CV content.
        The backend must enforce guardrails (no unrelated knowledge, no secrets, no arbitrary browsing).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
      responses:
        "200":
          description: Assistant reply
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    HealthResponse:
      type: object
      required: [status, timestamp]
      properties:
        status:
          type: string
          example: ok
        timestamp:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: invalid_request
        message:
          type: string
          example: The request is invalid.
        details:
          type: object
          additionalProperties: true

    CvSectionsResponse:
      type: object
      required: [lang, updatedAt, sections]
      properties:
        lang:
          type: string
          enum: [es, en]
        updatedAt:
          type: string
          format: date-time
        sections:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/CvSection"

    CvSection:
      type: object
      required: [id, title, items]
      properties:
        id:
          type: string
          example: experience
        title:
          type: string
          example: Experience
        items:
          type: array
          items:
            type: object
            additionalProperties: true

    CvDocument:
      type: object
      required: [lang, updatedAt, profile, experience, projects, skills]
      properties:
        lang:
          type: string
          enum: [es, en]
        updatedAt:
          type: string
          format: date-time
        profile:
          $ref: "#/components/schemas/Profile"
        experience:
          type: array
          items:
            $ref: "#/components/schemas/ExperienceItem"
        projects:
          type: array
          items:
            $ref: "#/components/schemas/ProjectItem"
        skills:
          type: array
          items:
            $ref: "#/components/schemas/SkillItem"
        education:
          type: array
          items:
            $ref: "#/components/schemas/EducationItem"
        certifications:
          type: array
          items:
            $ref: "#/components/schemas/CertificationItem"
        languages:
          type: array
          items:
            $ref: "#/components/schemas/LanguageItem"

    Profile:
      type: object
      required: [fullName, title, location, summary]
      properties:
        fullName:
          type: string
          example: Cristian Gimenez
        title:
          type: string
          example: Senior Full-Stack Developer (.NET / React)
        location:
          type: string
          example: Barcelona, Spain
        summary:
          type: string
          example: Senior developer with experience in .NET, Azure, and React.
        links:
          type: array
          items:
            $ref: "#/components/schemas/LinkItem"

    LinkItem:
      type: object
      required: [label, href]
      properties:
        label:
          type: string
          example: GitHub
        href:
          type: string
          example: https://github.com/<user>

    ExperienceItem:
      type: object
      required: [company, role, startDate, highlights]
      properties:
        company:
          type: string
          example: PayRetailers
        role:
          type: string
          example: Senior Full-Stack Developer
        location:
          type: string
          example: Barcelona, Spain
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        highlights:
          type: array
          items:
            type: string

    ProjectItem:
      type: object
      required: [name, description]
      properties:
        name:
          type: string
          example: CV
        description:
          type: string
          example: Bilingual CV website with CV-scoped chat.
        stack:
          type: array
          items:
            type: string
          example: [Next.js, .NET, Docker]
        links:
          type: array
          items:
            $ref: "#/components/schemas/LinkItem"

    SkillItem:
      type: object
      required: [category, items]
      properties:
        category:
          type: string
          example: Backend
        items:
          type: array
          items:
            type: string
          example: [.NET, ASP.NET Core, Azure Functions, Cosmos DB]

    EducationItem:
      type: object
      required: [institution, degree]
      properties:
        institution:
          type: string
        degree:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true

    CertificationItem:
      type: object
      required: [name]
      properties:
        name:
          type: string
        issuer:
          type: string
        date:
          type: string
          format: date

    LanguageItem:
      type: object
      required: [name, level]
      properties:
        name:
          type: string
          example: English
        level:
          type: string
          example: Professional

    ChatRequest:
      type: object
      required: [lang, messages]
      properties:
        lang:
          type: string
          enum: [es, en]
        messages:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/ChatMessage"
        temperature:
          type: number
          minimum: 0
          maximum: 2
          default: 0.3
        maxTokens:
          type: integer
          minimum: 64
          maximum: 2048
          default: 512

    ChatMessage:
      type: object
      required: [role, content]
      properties:
        role:
          type: string
          enum: [system, user, assistant]
        content:
          type: string

    ChatResponse:
      type: object
      required: [id, createdAt, message]
      properties:
        id:
          type: string
          example: chatcmpl_123
        createdAt:
          type: string
          format: date-time
        message:
          $ref: "#/components/schemas/ChatMessage"
        citations:
          type: array
          items:
            $ref: "#/components/schemas/ChatCitation"

    ChatCitation:
      type: object
      required: [sourceId, title]
      properties:
        sourceId:
          type: string
          example: content/es/experience.md
        title:
          type: string
          example: Experience
        snippet:
          type: string
          nullable: true
