// <auto-generated />
using System;
using CvIa.Infrastructure.Rag.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CvIa.Infrastructure.Rag.Persistence.Migrations;

[DbContext(typeof(RagDbContext))]
[Migration("20260329150805_InitRag")]
partial class InitRag
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CvIa.Domain.Rag.RagContentChunk", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("ChunkIndex")
                    .HasColumnType("integer")
                    .HasColumnName("chunk_index");

                b.Property<string>("DocumentKey")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("document_key");

                b.Property<Vector>("Embedding")
                    .IsRequired()
                    .HasColumnType("vector(1536)")
                    .HasColumnName("embedding");

                b.Property<string>("Lang")
                    .HasMaxLength(8)
                    .HasColumnType("character varying(8)")
                    .HasColumnName("lang");

                b.Property<string>("SectionId")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("section_id");

                b.Property<string>("SourceId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("source_id");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("text");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.HasKey("Id");

                b.HasIndex("SourceId", "Lang");

                b.HasIndex("SourceId", "DocumentKey", "ChunkIndex")
                    .IsUnique();

                b.ToTable("content_chunk", (string)null);
            });
#pragma warning restore 612, 618
    }
}
